FactoryGirl.define do
  factory :aparty do
    BalanceSheetDate "2017-03-21"
    HoldingPartyReference "MyString"
    PartyReference "MyString"
    PartyDescription "MyString"
    NIF "MyString"
    ActivitySector "MyString"
    CountryCode "MyString"
    SectorialCode "MyString"
    PartyType "MyString"
    Balcao "MyString"
    ZipCode "MyString"
    CodigoVigilanciaEspecial "MyString"
    PartyGroupReference "MyString"
    TotalGroupExposure "9.99"
    TotalPartyExposure "9.99"
    BPN_OverdueCredit "9.99"
    BPN_ReturnedCheques "9.99"
    BPN_OverdueCreditOther "9.99"
    BPN_BdPDefault "9.99"
    BPN_OverdueCreditBPNOther "9.99"
    NPLTeam "MyString"
    NPLTeamLeader "MyString"
    AssetManager "MyString"
    LegalManager "MyString"
  end
end
